# Generated by Django 5.2.1 on 2025-05-19 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='is_guest',
            field=models.BooleanField(default=True),
        ),
    ]
