# Generated by Django 5.2.1 on 2025-05-19 19:48

import web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_gameuser_is_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameplayer',
            name='color',
            field=models.CharField(default=web.utils.get_random_color, max_length=15),
        ),
        migrations.AlterField(
            model_name='gameuser',
            name='color',
            field=models.CharField(default=web.utils.get_random_color, max_length=15),
        ),
    ]
