# Generated by Django 5.2.1 on 2025-05-21 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_gameplayer_color_alter_gameuser_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
