# Generated by Django 5.2.1 on 2026-06-03 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_lobby_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='web.gameplayer'),
        ),
    ]
