# Generated by Django 5.2.1 on 2026-06-29 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_lobby_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='has_surrendered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
