# Generated by Django 5.2.1 on 2026-07-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_gameplayer_has_surrendered_alter_lobby_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='is_artificial',
            field=models.BooleanField(default=False),
        ),
    ]
