# Generated by Django 5.2.1 on 2026-07-11 21:23

import web.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_gameplayer_is_artificial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayer',
            name='name',
            field=models.CharField(default=web.utils.get_player_guest_name, max_length=64),
        ),
    ]
