# Generated by Django 5.2.1 on 2026-07-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_gameplayer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='previous_lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.lobby'),
        ),
    ]
